const fs = require('node:fs');
const path = require('node:path');

if (!process.env.FONT_URL) {
  throw new Error('FONT_URL environment variable is required. Set it (e.g. in .envrc or CI) before running the build.');
}

function extractFontSrcValue(css) {
  const match = css.match(/src:\s*([^;]+);/);
  return match ? match[1].trim() : null;
}

const outDir = path.join(__dirname, '..', 'src', 'fonts');
fs.mkdirSync(outDir, { recursive: true });

const fontCssPath = path.join(__dirname, 'fonts.template');
let fontCss = fs.readFileSync(fontCssPath, 'utf8');
fontCss = fontCss.replaceAll(/url\(\s*(?:""|'')?\s*\)/g, `url("${process.env.FONT_URL}")`);

const fontSrcValue = extractFontSrcValue(fontCss);

fs.writeFileSync(path.join(outDir, 'fonts.css'), fontCss);

if (fontSrcValue) {
  const raw = fontSrcValue.replaceAll(/\s+/g, ' ').trim();
  const scssContent = `// Generated by scripts/fBuilder.js - do not edit manually
$font-src: ${raw};
`;
  fs.writeFileSync(path.join(outDir, '_font-variables.scss'), scssContent);
}
