# Base SonarQube configuration for City of Helsinki Frontend projects
sonar.projectKey=City-of-Helsinki_helsinki-design-system
sonar.organization=city-of-helsinki
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.sources=src

sonar.exclusions= \
  **/__mocks__/**/*, \
  **/__snapshots__/*, \
  **/*.d.ts, \
  **/*.png, \
  **/*.jpg, \
  **/*.zip

sonar.test.inclusions= \
  **/__tests__/**/*, \
  **/*.test.js, \
  **/*.test.ts, \
  **/*.test.jsx, \
  **/*.test.tsx

sonar.coverage.exclusions= \
  **/*.stories.js, \
  **/*.stories.ts, \
  **/*.stories.jsx, \
  **/*.stories.tsx, \
  **/example/**/*, \
  **/examples/**/*, \
  **/storybookStatic/**/*, \
  **/batch.options.ts, \
  **/testUtils/**/*, \
  **/*testUtil.tsx, \
  **/*.testUtil.tsx, \
  src/components/cookieConsent/components/StoryComponent.tsx, \
  src/components/cookieConsentCore/storyComponents/**/*, \
  src/components/login/graphQLModule/demoData/MyProfileQuery.ts, \
  src/internal/**/*, \
  src/utils/PlayWrightComponentHandler.tsx, \
  src/utils/playWrightHelpers.ts, \
  src/utils/mockWindowLocation.ts, \
  src/utils/testHelpers.ts

sonar.cpd.exclusions= src/icons/**/*
