name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - development
      - master
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
