# this is reference workflow to run e2e tests and get test results
name: e2e-tests

on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string

jobs:
  e2e-tests:
    # needs to match the playwright-docker image version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: download all artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-${{ inputs.commit_sha }}
          path: ./packages

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvmrc

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: setup node ${{ steps.nvmrc.outputs.NODE_VERSION }}
        uses: actions/setup-node@v6
        with:
          node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: install playwright browser and OS dependencies
        run: pnpm playwright-install
        working-directory: ./e2e

      - name: run tests
        run: pnpm start
        working-directory: ./e2e

      - name: upload test results in case of failure
        uses: actions/upload-artifact@v7
        with:
          name: e2e_test_report
          path: e2e/report/
          include-hidden-files: true
        if: failure()

      - name: upload screenshot differences in case of failure
        uses: actions/upload-artifact@v7
        with:
          name: e2e_test_results
          path: e2e/test-results/
        if: failure()

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && github.actor != 'dependabot[bot]'
        with:
          files: |
            e2e/report/**/*.xml
            